# Generated by Django 4.1.7 on 2023-03-23 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MenuApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Name of item')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('sub_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MenuApp.menu', verbose_name='Menu')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Subitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Name of subitem')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('sub_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MenuApp.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Subitem',
                'verbose_name_plural': 'Subitems',
            },
        ),
        migrations.DeleteModel(
            name='Submenu',
        ),
    ]
